### ISSUE TITLE
Add user avatar

### ISSUE THREAD

**Issue by iprnd** [iprnd/Carista#11]
- Folder in firebase storage -> users avatars
 - Database -> users tree -> user info

**Comment by iprnd** [comment]
Add user nickname

**Comment by Watchwalker** [comment]
### **Features**

- Added user avatars in Firebase and displayed in Users Tab in a Circular ImageView.
> Users can now click on the avatar to change it from either camera or any other way.

- Added user nicknames in Firebase and displayed in Users Tab under user avatar.
> By default, if no nickname was given, authentication method's identifier is displayed (eg. email, gmail, Facebook, ...).

> Clicking on username shows hidden EditText and Button views to insert a new nickname.

> These views disappear after clicking and changing username.


### **Enhancements**

- Added a light background color to the entire application.
- Added styles and drawable backgrounds to EditText, RecycleView and ImageView widgets to look better.
- Changed FloatingActionButton icon to a pencil.
- Changed Tab bar color: tabs names are displayed properly now.
- Moved Upload Activity to Tab 2 and removed old standalone activity.

### **Bug Fixes**

- Fixed Logout button floating over keyboard upon its opening when trying to change the nickname.
- Fixed last RecycleView item in Posts tab as it was being half-cropped on its end.
- Fixed overall control and UI design issues.
