### ISSUE TITLE
Posts likes

### ISSUE THREAD

**Issue by iprnd** [iprnd/Carista#19]
- Likes counter badge
 - Like button

**Comment by Watchwalker** [comment]
### **Features**

Added likes feature for each post. This simply implies that:

1. Users can now like any post or remove that like.
2. The heart shape will be red once liked, and empty if not liked.
3. The heart shape will appear red on all liked posts even after closing the app.
4. A likes count is displayed to provide how many likes were given for a certain post.
5. This count label includes the "including you" if the user liked this post.
6. This count refreshes on the second, which means any change from the outside will appear live.
7. The like button has state animations upon liking or removing the like (heart pops up).
