### ISSUE TITLE
Firestore migration

### ISSUE THREAD

**Issue by iprnd** [iprnd/Carista#29]
- Migrate data to firestore
- Pagination (for lazy loading) [https://firebase.google.com/docs/firestore/query-data/query-cursors?authuser=0#add_a_simple_cursor_to_a_query](url)

**Comment by Watchwalker** [comment]
### **Features**

- Mapped old Firebase Real-time Database's schema to a consistent schema
> Migrated from Posts -> UsersID -> PostsId -> { PostModel v1} to Posts -> PostsId -> {PostModel v2}.

_This affected the entire path definition in the Data class for uploading and downloading data, which was fixed for Likes, Comments, Posts Loading, User Posts Loading, Uploading Posts and setting Post Details methods._

- Posts now load 5 by 5 upon vertical scrolling end detection.
> Single value listener grabbing 5 posts on the start, saving the last item and continues from this item to the next 5 using DatabaseReference.startAt(postId).limitToFirst(6) method and skipping the 1st element as it was already displayed before.

- Migrated RoomDatabase schema to PostModel v2.
> Room now saves the last 5 posts and displays them to the user when offline.

_At this point, likes and comments remain on their previous real-time state, and are not affected by the single value listener as they work independently from lazy loading mechanism._

### **Fixes**

- Fixed Post Title & Post Image backgrounds for EditText and ImageView to match Dark & White Themes.

- As a result of migration, animation of the Like Button is now fixed and pops-up once clicked.
